namespace: 5g-core

images:
  mongodb: mongo:6.0
  open5gs: docker.io/open5gs/open5gs:latest
  ueransim: docker.io/gradiant/ueransim:3.2.6

resources:
  small:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

network:
  hostNetworkForRan: true

subscriber:
  imsi: "001010000000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  dnn: "internet"
  mcc: "001"
  mnc: "01"
  tac: "1"
  sst: "1"
  sd: "000001"
